services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: medika
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - ci4net

  db:
    image: mysql:8.0
    container_name: medika_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medika_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - ci4net

networks:
  ci4net:

volumes:
  db_data:
